### ISSUE TITLE
Can't get Pygame

### ISSUE THREAD

**Issue by ghost** [crkellen/pygameClicker#1]
The pygame-1.9.3-cp35-cp35m-win_amd64 is not on the website you specified, could you put a new version that we can use?

**Comment by crkellen** [comment]
Apologies, I wasn't checking the email tied to this account as often as others.
[This seems to be the correct link.](https://files.pythonhosted.org/packages/0b/8c/109e25163da7144c0767b33d41d4674c4aa8cb88d18aa29fc02341f3981a/pygame-1.9.3-cp35-cp35m-win_amd64.whl)
Which I got from [here.](https://pypi.org/project/pygame/1.9.3/#files)
