### ISSUE TITLE
Problem 

### ISSUE THREAD

**Issue by swartztz** [crkellen/pygameClicker#2]
When I click on the link it sends me to an error 404 page.

**Comment by crkellen** [comment]
Looks like you can download it from here: https://www.pygame.org/download.shtml
Specifically: https://pypi.python.org/packages/61/06/3c25051549c252cc6fde01c8aeae90b96831370884504fe428a623316def/pygame-1.9.3.tar.gz#md5=ac744ea6952b68d5f2b6d02a6d8e836c

**Comment by crkellen** [comment]
Alternatively, check #1 which already answers this.
